export default {
  crocotaco: 'Ed',
  jimboslicethat: 'James',
  Felux: 'David',
  hunnyj: 'Hunter',
  'Dan TheBigCat': 'Dan',
  gruebchen: 'Jacob',
  kjames713: 'Kenny',
  joseeWho: 'Josee',
  salsaparker: 'Ler',
  squibs: 'Zach (Squibs)',
  theonlycarlee: 'Carlee',
  jonibwhoeversheb: 'Joni',
  PonchoMcGee: 'Josh Houghton',
  notablytipsy: 'Purj',
  lottaFLOPS: 'Connor',
  Gingernaut: 'Tyler',
  Tinkerbell: 'Carol',
  bkuddy: 'Brett'
}
