# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR Build & Test

on:
  push:
    branches:
      - '*/*'
      - '*'
      - '!master'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set node version to ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          yarn
          npm run build --if-present
          npm test
        env:
          CI: true
